// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2876.PracticeBot2018;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveTrainTalonSRX1;
    public static WPI_TalonSRX driveTrainTalonSRX2;
    public static SpeedControllerGroup driveTrainSpeedControllerGroupLeft;
    public static WPI_TalonSRX driveTrainTalonSRX3;
    public static WPI_TalonSRX driveTrainTalonSRX4;
    public static SpeedControllerGroup driveTrainSpeedControllerGroupRight;
    public static DifferentialDrive driveTrainDifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainTalonSRX1 = new WPI_TalonSRX(0);
        
        
        driveTrainTalonSRX2 = new WPI_TalonSRX(1);
        
        
        driveTrainSpeedControllerGroupLeft = new SpeedControllerGroup(driveTrainTalonSRX1, driveTrainTalonSRX2  );
        LiveWindow.addActuator("DriveTrain", "Speed Controller Group Left", driveTrainSpeedControllerGroupLeft);
        
        driveTrainTalonSRX3 = new WPI_TalonSRX(2);
        
        
        driveTrainTalonSRX4 = new WPI_TalonSRX(3);
        
        
        driveTrainSpeedControllerGroupRight = new SpeedControllerGroup(driveTrainTalonSRX3, driveTrainTalonSRX4  );
        LiveWindow.addActuator("DriveTrain", "Speed Controller Group Right", driveTrainSpeedControllerGroupRight);
        
        driveTrainDifferentialDrive = new DifferentialDrive(driveTrainSpeedControllerGroupLeft, driveTrainSpeedControllerGroupRight);
        LiveWindow.addActuator("DriveTrain", "Differential Drive", driveTrainDifferentialDrive);
        driveTrainDifferentialDrive.setSafetyEnabled(true);
        driveTrainDifferentialDrive.setExpiration(0.1);
        driveTrainDifferentialDrive.setMaxOutput(1.0);


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
